// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "common": {
    "cancel": "取消",
    "changelog": {
      "empty": "暂无更新日志",
      "fetchFailed": "获取更新日志失败",
      "loadingTip": "加载更新日志中...",
      "sourceNote": "💡 更新日志来自本地 CHANGELOG.md 文件",
      "title": "更新日志",
      "viewTooltip": "查看更新日志"
    },
    "placeholder": "占位文本",
    "refresh": "刷新",
    "stream": {
      "readFailed": "无法读取灵创创作助手响应流"
    },
    "theme": {
      "dark": "深色模式",
      "light": "浅色模式",
      "system": "跟随系统"
    },
    "userMenu": {
      "admin": "管理员",
      "adminBadge": "👑 管理员",
      "adminOnly": "只有管理员可以访问用户管理",
      "changePassword": "修改密码",
      "confirmPassword": "确认密码",
      "confirmPasswordPlaceholder": "请再次输入新密码",
      "confirmPasswordRequired": "请确认新密码",
      "loggedOut": "已退出登录",
      "logout": "退出登录",
      "logoutFailed": "退出登录失败",
      "newPassword": "新密码",
      "newPasswordPlaceholder": "请输入新密码（至少6个字符）",
      "newPasswordRequired": "请输入新密码",
      "passwordChangeFailed": "修改密码失败",
      "passwordChanged": "密码修改成功",
      "passwordMin": "密码至少6个字符",
      "passwordMismatch": "两次输入的密码不一致",
      "submitChanges": "确认修改",
      "trustLevel": "Trust Level: {{level}}",
      "trustLevelBadge": "🎖️ Trust Level {{level}}",
      "userManagement": "用户管理"
    }
  },
  "errors": {
    "auth": {
      "unauthorized": "未登录"
    },
    "conflict": {
      "error": "资源冲突"
    },
    "dynamic_detail": "请求处理失败，请稍后重试",
    "http": {
      "badRequest": "请求参数错误",
      "errorWithStatus": "请求失败 ({{status}})",
      "forbidden": "没有权限访问",
      "notFound": "请求的资源不存在",
      "serviceUnavailable": "服务暂时不可用，请稍后重试",
      "unauthorized": "登录状态已失效，请重新登录"
    },
    "http_error": "{{detail}}",
    "internal": {
      "error": "服务器内部错误"
    },
    "network": {
      "error": "网络错误，请检查网络连接"
    },
    "not_found": {
      "chapter": "章节不存在",
      "outline": "大纲不存在",
      "project": "项目不存在"
    },
    "requestFailed": "请求失败",
    "task": {
      "batchListFailed": "获取批量生成任务失败",
      "cancelBatchFailed": "取消批量生成任务失败",
      "cancelFailed": "取消任务失败",
      "cancelled": "任务已取消",
      "clearFailed": "清理任务记录失败",
      "createChapterFailed": "创建章节生成任务失败",
      "createFailed": "创建任务失败",
      "deleteFailed": "删除任务失败",
      "failed": "任务失败",
      "listFailed": "获取任务列表失败",
      "queryStatusFailed": "查询任务状态失败"
    },
    "unknown": "未知错误",
    "validation": {
      "config": "配置数据格式错误",
      "error": "请求参数验证失败",
      "failed": "请求参数验证失败"
    }
  }
}
