// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "common": {
    "placeholder": "占位文本"
  },
  "errors": {
    "unknown": "未知错误"
  }
}
