// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "characters": {
    "buttons": {
      "addSubCareer": "+ 添加副职业",
      "aiGenerateCharacter": "AI生成角色",
      "aiGenerateOrganization": "AI生成组织",
      "cancel": "取消",
      "create": "创建",
      "createCharacter": "创建角色",
      "createOrganization": "创建组织",
      "delete": "删除",
      "exportBatch": "批量导出 ({{n}})",
      "generate": "生成",
      "import": "导入",
      "save": "保存"
    },
    "createModal": {
      "characterTitle": "创建角色",
      "organizationTitle": "创建组织"
    },
    "editModal": {
      "characterTitle": "编辑角色",
      "organizationTitle": "编辑组织"
    },
    "empty": {
      "noCharacters": "暂无角色",
      "noData": "暂无数据",
      "noOrganizations": "暂无组织",
      "none": "还没有角色或组织，开始创建吧！"
    },
    "form": {
      "age": "年龄",
      "appearance": "外貌描写",
      "backgroundCharacter": "角色背景",
      "backgroundOrganization": "组织背景",
      "backgroundSetting": "背景设定",
      "careerInfo": "职业信息",
      "careerInfoOptional": "职业信息（可选）",
      "careerMaxStage": "（最高{{stage}}阶）",
      "color": "代表颜色",
      "currentStage": "当前阶段",
      "currentStageTooltip": "主职业当前修炼到的阶段",
      "gender": "性别",
      "location": "所在地",
      "mainCareer": "主职业",
      "mainCareerTooltip": "角色的主要修炼职业",
      "membersEmpty": "暂无成员，请在组织管理中添加",
      "membersHint": "💡 请前往「组织管理」页面添加或管理组织成员",
      "membersTooltip": "成员信息由组织管理模块维护，此处仅展示",
      "motto": "格言/口号",
      "nameCharacter": "角色名称",
      "nameOrganization": "组织名称",
      "organizationMembers": "主要成员",
      "organizationPurpose": "组织目的",
      "organizationType": "组织类型",
      "personality": "性格特点",
      "powerLevel": "势力等级",
      "powerLevelTooltip": "0-100的数值",
      "relationshipsReadonly": "人际关系（由关系管理维护）",
      "requirements": "其他要求",
      "roleType": "角色定位",
      "subCareers": "副职业"
    },
    "gender": {
      "female": "女",
      "male": "男",
      "other": "其他"
    },
    "generateModal": {
      "characterTitle": "AI生成角色",
      "organizationTitle": "AI生成组织"
    },
    "import": {
      "charactersCount": "角色: {{n}} 个",
      "charactersLabel": "角色:",
      "confirmImport": "确认导入",
      "doneTitle": "导入完成",
      "failedCount": "❌ 失败: {{n}} 个",
      "fileVersion": "文件版本:",
      "organizationsCount": "组织: {{n}} 个",
      "organizationsLabel": "组织:",
      "previewTitle": "导入预览",
      "skippedCount": "⚠️ 跳过: {{n}} 个",
      "successCount": "✅ 成功导入: {{n}} 个",
      "validateFailed": "文件验证失败",
      "warningsLabel": "⚠️ 警告:",
      "willImport": "将要导入:"
    },
    "importModal": {
      "description": "选择之前导出的角色/组织JSON文件进行导入",
      "noteIgnoreCareers": "职业信息如不存在将被忽略",
      "noteJsonFormat": "支持导入.json格式的角色/组织文件",
      "noteSkipDuplicates": "重复名称的角色/组织将被跳过",
      "notesTitle": "说明：",
      "selectFile": "选择文件",
      "title": "导入角色/组织"
    },
    "placeholder": {
      "age": "如：25岁",
      "appearance": "描述角色的外貌特征...",
      "backgroundCharacter": "描述角色的背景故事...",
      "backgroundForGen": "简要描述角色背景和故事环境...",
      "backgroundOrganization": "描述组织的背景故事...",
      "color": "如：金色",
      "gender": "性别",
      "location": "总部位置",
      "motto": "组织的宗旨、格言或口号",
      "nameCharacter": "角色名称",
      "nameCharacterOptional": "如：张三、李四（可选，AI会自动生成）",
      "nameOrganization": "组织名称",
      "nameOrganizationOptional": "如：天剑门、黑龙会（可选，AI会自动生成）",
      "organizationBackgroundForGen": "简要描述组织的背景和环境...",
      "organizationPurpose": "描述组织的宗旨和目标...",
      "organizationType": "如：门派、帮派",
      "organizationTypeForGen": "如：门派、帮派、公司、学院（可选，AI会根据世界观生成）",
      "personality": "描述角色的性格特点...",
      "requirements": "其他特殊要求...",
      "selectMainCareer": "选择主职业",
      "selectRoleType": "选择角色定位",
      "selectSubCareer": "选择副职业",
      "stage": "阶段"
    },
    "role": {
      "antagonist": "反派",
      "protagonist": "主角",
      "supporting": "配角"
    },
    "tabs": {
      "all": "全部 ({{n}})",
      "characters": "角色 ({{n}})",
      "organizations": "组织 ({{n}})"
    },
    "title": "角色与组织管理",
    "toast": {
      "aiCharacterSuccess": "AI生成角色成功",
      "aiGenerateFailed": "AI生成失败",
      "aiOrganizationSuccess": "AI生成组织成功",
      "characterCreated": "角色创建成功",
      "createFailed": "创建失败",
      "deleteFailed": "删除失败",
      "deleteSuccess": "删除成功",
      "exportCountSuccess": "成功导出 {{n}} 个角色/组织",
      "exportFailed": "导出失败",
      "exportSuccess": "导出成功",
      "generateFailed": "生成失败: {{error}}",
      "importFailed": "导入失败",
      "organizationCreated": "组织创建成功",
      "progressComplete": "生成完成！",
      "progressPrepareCharacter": "准备生成角色...",
      "progressPrepareOrganization": "准备生成组织...",
      "selectForExport": "请至少选择一个角色或组织",
      "updateFailed": "更新失败",
      "updateSuccess": "更新成功"
    },
    "toolbar": {
      "clearSelection": "取消选择",
      "selectAll": "全选",
      "selected": "已选 {{n}} 个"
    },
    "validation": {
      "nameCharacterRequired": "请输入角色名称",
      "nameOrganizationRequired": "请输入组织名称",
      "organizationPurposeRequired": "请输入组织目的",
      "organizationTypeRequired": "请输入组织类型",
      "roleTypeRequired": "请选择角色定位",
      "stageRequired": "阶段",
      "subCareerRequired": "请选择副职业"
    }
  },
  "common": {
    "cancel": "取消",
    "changelog": {
      "empty": "暂无更新日志",
      "fetchFailed": "获取更新日志失败",
      "loadingTip": "加载更新日志中...",
      "sourceNote": "💡 更新日志来自本地 CHANGELOG.md 文件",
      "title": "更新日志",
      "viewTooltip": "查看更新日志"
    },
    "placeholder": "占位文本",
    "refresh": "刷新",
    "stream": {
      "readFailed": "无法读取灵创创作助手响应流"
    },
    "theme": {
      "dark": "深色模式",
      "light": "浅色模式",
      "system": "跟随系统"
    },
    "userMenu": {
      "admin": "管理员",
      "adminBadge": "👑 管理员",
      "adminOnly": "只有管理员可以访问用户管理",
      "changePassword": "修改密码",
      "confirmPassword": "确认密码",
      "confirmPasswordPlaceholder": "请再次输入新密码",
      "confirmPasswordRequired": "请确认新密码",
      "loggedOut": "已退出登录",
      "logout": "退出登录",
      "logoutFailed": "退出登录失败",
      "newPassword": "新密码",
      "newPasswordPlaceholder": "请输入新密码（至少6个字符）",
      "newPasswordRequired": "请输入新密码",
      "passwordChangeFailed": "修改密码失败",
      "passwordChanged": "密码修改成功",
      "passwordMin": "密码至少6个字符",
      "passwordMismatch": "两次输入的密码不一致",
      "submitChanges": "确认修改",
      "trustLevel": "Trust Level: {{level}}",
      "trustLevelBadge": "🎖️ Trust Level {{level}}",
      "userManagement": "用户管理"
    }
  },
  "errors": {
    "auth": {
      "unauthorized": "未登录"
    },
    "conflict": {
      "error": "资源冲突"
    },
    "dynamic_detail": "请求处理失败，请稍后重试",
    "http": {
      "badRequest": "请求参数错误",
      "errorWithStatus": "请求失败 ({{status}})",
      "forbidden": "没有权限访问",
      "notFound": "请求的资源不存在",
      "serviceUnavailable": "服务暂时不可用，请稍后重试",
      "unauthorized": "登录状态已失效，请重新登录"
    },
    "http_error": "{{detail}}",
    "internal": {
      "error": "服务器内部错误"
    },
    "network": {
      "error": "网络错误，请检查网络连接"
    },
    "not_found": {
      "chapter": "章节不存在",
      "outline": "大纲不存在",
      "project": "项目不存在"
    },
    "requestFailed": "请求失败",
    "task": {
      "batchListFailed": "获取批量生成任务失败",
      "cancelBatchFailed": "取消批量生成任务失败",
      "cancelFailed": "取消任务失败",
      "cancelled": "任务已取消",
      "clearFailed": "清理任务记录失败",
      "createChapterFailed": "创建章节生成任务失败",
      "createFailed": "创建任务失败",
      "deleteFailed": "删除任务失败",
      "failed": "任务失败",
      "listFailed": "获取任务列表失败",
      "queryStatusFailed": "查询任务状态失败"
    },
    "unknown": "未知错误",
    "validation": {
      "config": "配置数据格式错误",
      "error": "请求参数验证失败",
      "failed": "请求参数验证失败"
    }
  },
  "settings": {
    "buttons": {
      "delete": "删除",
      "deleteConfig": "删除配置",
      "fetch": "获取",
      "refresh": "刷新",
      "reset": "重置",
      "save": "保存",
      "saveSettings": "保存设置",
      "test": "测试",
      "testConnection": "测试连接",
      "testing": "测试中..."
    },
    "confirm": {
      "cancel": "取消",
      "deleteContent": "确定要删除所有设置吗？此操作不可恢复。",
      "deleteTitle": "删除设置",
      "ok": "确定",
      "resetContent": "确定要重置为默认值吗？",
      "resetTitle": "重置设置"
    },
    "cover": {
      "apiKeyLabel": "封面图片 API Key",
      "apiKeyPlaceholder": "输入封面图片 API Key",
      "apiKeyRequired": "请输入封面图片 API Key",
      "baseUrlLabel": "封面图片 API 地址",
      "disableOption": "停用封面图片生成",
      "enableOption": "启用封面图片生成",
      "enabledLabel": "封面图片生成功能",
      "modelLabel": "封面图片模型",
      "modelRequired": "请输入封面图片模型名称",
      "providerLabel": "封面图片 Provider",
      "providerRequired": "请选择封面图片 Provider",
      "saveButton": "保存封面配置",
      "testButton": "测试封面接口"
    },
    "defaultAlert": {
      "descFromEnv": "当前显示的是从服务器 ",
      "descSuffix": " 文件读取的默认配置。",
      "message": "使用 .env 文件中的默认配置",
      "saveNote": "点击\"保存设置\"后，配置将保存到数据库并同步更新到 ",
      "saveNoteSuffix": " 文件。",
      "savedMessage": "使用已保存的个人配置"
    },
    "form": {
      "apiBaseUrl": "API 地址",
      "apiBaseUrlTooltip": "API的基础URL地址",
      "apiKey": "API 密钥",
      "apiKeyTooltip": "你的API密钥，将加密存储",
      "apiProvider": "API 提供商",
      "apiProviderTooltip": "选择你的AI服务提供商",
      "disableThinking": "关闭模型思考",
      "disableThinkingTooltip": "适用于思考型模型：开启后模型跳过思考阶段直接输出正文，可显著减少等待时间与token消耗；对不支持此选项的服务无影响",
      "llmModel": "模型名称",
      "llmModelTooltip": "AI模型的名称，如 gpt-4, gpt-3.5-turbo",
      "maxTokens": "最大 Token 数",
      "maxTokensTooltip": "单次请求的最大token数量",
      "systemPrompt": "系统提示词",
      "systemPromptTooltip": "设置全局系统提示词，每次AI调用时都会自动使用。可用于设定AI的角色、语言风格等",
      "temperature": "温度参数",
      "temperatureTooltip": "控制输出的随机性，值越高越随机（0.0-2.0）"
    },
    "language": {
      "description": "切换后立即生效并保存；登录后以账号偏好为准",
      "enLabel": "English",
      "label": "界面语言 / Interface language",
      "savePreferenceFailed": "保存界面语言偏好失败:",
      "syncFailed": "已在本地生效，但同步到服务器失败，仅对本浏览器有效。",
      "updated": "界面语言已更新",
      "zhLabel": "简体中文"
    },
    "mcp": {
      "configChangedBody": "检测到您修改了 API 配置（提供商、地址或模型），为确保 MCP 插件正常工作，系统已自动禁用所有插件。",
      "configChangedPresetBody": "切换到预设「{{name}}」后，API 配置发生了变化。为确保 MCP 插件正常工作，系统已自动禁用所有插件。",
      "configChangedTitle": "API 配置已更改",
      "goToMcp": "前往 MCP 页面",
      "later": "稍后处理",
      "step1": "前往 MCP 插件管理页面",
      "step2": "重新进行\"模型能力检查\"",
      "step3": "确认新模型支持 Function Calling 后再启用插件",
      "stepsLabel": "请完成以下步骤："
    },
    "modelSelect": {
      "clickToFetch": "点击输入框自动获取，或直接输入模型名称",
      "fetchEmpty": "未能获取到模型列表，可直接输入模型名称",
      "fetching": "正在获取模型列表...",
      "loading": "加载中...",
      "manualDesc": "手动输入的模型名称",
      "refreshTooltip": "重新获取模型列表",
      "useTyped": "使用 \"{{name}}\""
    },
    "placeholder": {
      "apiKeyBuiltIn": "使用后端内置密钥",
      "modelDesktop": "输入模型名称或点击获取",
      "modelMobile": "输入或选择模型",
      "systemPrompt": "例如：你是一个专业的小说创作助手，请用生动、细腻的文字进行创作..."
    },
    "presetModal": {
      "apiKeyBuiltInPlaceholder": "使用后端内置密钥（不会暴露）",
      "apiKeyLabel": "API Key",
      "apiKeyRequired": "请输入API Key",
      "baseUrlLabel": "API Base URL",
      "cancel": "取消",
      "createTitle": "创建预设",
      "descriptionLabel": "预设描述",
      "descriptionMax": "描述不能超过200个字符",
      "descriptionPlaceholder": "例如：用于日常写作任务（可选）",
      "editTitle": "编辑预设",
      "fetchTooltip": "获取模型列表",
      "maxTokensLabel": "最大Tokens",
      "modelLabel": "模型名称",
      "modelPlaceholder": "输入模型名称或点击获取",
      "modelRequired": "请选择或输入模型名称",
      "modelTooltip": "AI模型的名称，点击下拉框自动获取可用模型",
      "nameLabel": "预设名称",
      "nameMax": "名称不能超过50个字符",
      "namePlaceholder": "例如：工作账号-GPT4",
      "nameRequired": "请输入预设名称",
      "providerLabel": "API 提供商",
      "providerPlaceholder": "选择提供商",
      "providerRequired": "请选择",
      "required": "必填",
      "save": "保存",
      "systemPromptLabel": "系统提示词",
      "systemPromptPlaceholder": "例如：你是一个专业的小说创作助手...（可选）",
      "temperatureLabel": "温度"
    },
    "presets": {
      "activate": "激活",
      "activeTag": "激活中",
      "apiTestFailed": "API 测试失败",
      "chapterAnalysisDefault": "当前未指定章节内容分析预设，将使用默认API配置。",
      "chapterAnalysisDesc": "指定章节内容分析使用的预设；未选择时使用默认的文本模型配置。",
      "chapterAnalysisPreferred": "章节内容分析将优先使用所选预设。",
      "chapterAnalysisTag": "章节分析",
      "chapterAnalysisTitle": "章节内容分析 API 配置",
      "connectionOk": "✓ API 连接正常",
      "createFirst": "创建第一个预设",
      "createFromCurrent": "从当前创建",
      "createNew": "新建预设",
      "createdPrefix": "创建于:",
      "defaultOption": "默认API配置",
      "delete": "删除",
      "deleteConfirm": "确定删除此预设吗？",
      "edit": "编辑",
      "emptyText": "暂无预设配置",
      "errorLabel": "错误信息:",
      "manageHint": "管理你的API配置预设，快速切换不同的配置",
      "modelLabel": "模型：",
      "providerLabel": "提供商：",
      "responseTimeLabel": "响应时间：",
      "suggestionsLabel": "💡 建议:",
      "temperatureTag": "温度: {{value}}",
      "test": "测试",
      "testFailedTitle": "测试失败",
      "testPassAlert": "预设配置测试通过，可以正常使用",
      "testProblemAlert": "预设配置存在问题，请检查后重试",
      "testSuccessTitle": "测试成功"
    },
    "provider": {
      "xiaomiMimoAdapter": "Xiaomi MiMo 内置适配器",
      "xiaomiMimoBuiltIn": "Xiaomi MiMo（内置）",
      "xiaomiMimoBuiltInDesc": "使用 OpenAI 兼容格式与内置服务地址。真实 Key 仅由后端环境变量提供，前端和数据库不会保存该 Key。",
      "xiaomiMimoDefaultModelDesc": "Xiaomi MiMo 官方内置推荐模型",
      "xiaomiMimoPresetDesc": "使用后端内置 Key 和 OpenAI 兼容接口地址，预设中不会保存真实 Key。"
    },
    "subtitle": "配置AI接口参数，管理多个API配置预设",
    "tabs": {
      "cover": "图片模型配置",
      "current": "文本模型配置",
      "presets": "配置预设"
    },
    "testResult": {
      "configOk": "✓ API 配置正确，可以正常使用",
      "errorLabel": "错误信息:",
      "errorType": "错误类型:",
      "previewLabel": "AI 响应预览:",
      "responseTime": "⚡ 响应时间:",
      "suggestionsLabel": "💡 解决建议:"
    },
    "title": "AI API 设置",
    "toast": {
      "activateFailed": "激活失败",
      "chapterAnalysisPresetFailed": "设置章节内容分析API配置失败",
      "chapterAnalysisPresetReset": "章节内容分析已恢复使用默认API配置",
      "chapterAnalysisPresetSet": "已设置章节内容分析专用API配置",
      "checkBackend": "请确认后端服务是否正常运行",
      "checkNetwork": "请检查网络连接",
      "configIncomplete": "请先填写完整的配置信息",
      "coverConfigIncomplete": "请先填写完整的封面图片配置信息",
      "coverTestFailed": "封面图片接口测试失败",
      "coverTestSuccess": "封面图片接口测试成功",
      "deleteFailed": "删除设置失败",
      "deleteFailedShort": "删除失败",
      "deleted": "设置已删除",
      "disablingMcp": "正在禁用 MCP 插件...",
      "fillKeyAndUrl": "请先填写 API 密钥和 API 地址",
      "loadFailed": "加载设置失败",
      "mcpDisabled": "已禁用所有 MCP 插件",
      "modelsFetchFailed": "获取模型列表失败",
      "modelsFetched": "成功获取 {{n}} 个可用模型",
      "presetActivated": "已激活预设: {{name}}",
      "presetCreated": "预设已创建",
      "presetDeactivated": "配置已更改，预设激活状态已取消",
      "presetDeleted": "预设已删除",
      "presetUpdated": "预设已更新",
      "presetsLoadFailed": "加载预设失败",
      "resetDone": "已重置为默认值，请点击保存",
      "saveFailed": "保存设置失败",
      "saved": "设置已保存",
      "testFailed": "测试失败",
      "testFailedSeeDetails": "API 测试失败，请查看详细信息",
      "testRequestFailed": "测试请求失败",
      "testSuccess": "测试成功！响应时间: {{ms}}ms"
    },
    "validation": {
      "apiKeyRequired": "请输入API密钥",
      "baseUrlRequired": "请输入API地址",
      "maxTokensRequired": "请输入最大token数",
      "modelRequired": "请输入或选择模型名称",
      "positiveNumber": "请输入大于0的数字",
      "providerRequired": "请选择API提供商",
      "urlInvalid": "请输入有效的URL"
    }
  }
}
