name: Issue Translator

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Translate issue or comment (non-English -> English)
        uses: usthe/issues-translate-action@v2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
